/*
 * Copyright 2016-2017 Symphony Application Authentication - Symphony LLC
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.symphony.symphony.client;

import lombok.Data;

import java.io.Serializable;

/**
 * AuthenticateResponse - This is a model class that contain both the Application Token and Symphony Token for the
 * Extension API to validate the Client Application
 */

@Data
public class AuthenticateResponse implements Serializable {

    /**
     * Unique identifier of the app.
     */
    private String appId;

    /**
     * Token generated by application
     */
    private String appToken;

    /**
     * Token generated by Symphony
     */
    private String symphonyToken;
}

